### PR TITLE
Fix inspections

### PR DESCRIPTION
**Pull request by praseodym**
General cleanup: fixes many code style warnings/notices as reported by IntelliJ IDEA's inspections.

### CODE REVIEW

**Comment by jricher** [comment]
Thanks for this patch. We can take some of these, but probably not all of them. We also need to update our checkstyle settings to scan for Java 1.7 paradigms, too.

**Comment by jricher** [comment]
Rebased and patched, applied as 9e74e40453f0a6c74cc0827ea85505c1c56a1746 13f5e4f8a6aa5d457ef2aa2d1739c046e55a0abb 6dc2b2cb5ede2803c9f5461e08e97e0c4f4fed5f

**Comment by praseodym** [comment]
Cheers! Any reason why the redundant initialisers commit has not been merged?

**Comment by jricher** [comment]
Consistency in style. I'd rather have all variables that are defined on their own be initialized explicitly, instead of only when Java requires it. It's a habit I got into a long time ago and empty initializers look funny to me in Java now. 

I also pulled out a couple places that had collapsed an if/else into a boolean block because I believe the former to be more readable and understandable at a glance (at least in these specific cases).

Thanks very much for the patch!

**Comment by praseodym** [comment]
That's fair, code style is personal preference. Thanks for merging!

**Pull request closed without merging**
