### PR TITLE
add indexes on certain fields to shorten time taken to issue a new ac…

### PR DESCRIPTION
**Pull request by MusharrafSakran**
apply indexes on certain db fields to shorten the time needed for:
1- issuing a new access token.
2- scheduled tasks for expired access tokens.
3- scheduled tasks for expired refresh tokens.
4- scheduled tasks for orphaned  tokens.

without these indexes the token issuing request may take over 1 minute to reply after huge number of access tokens related rows in db has been inserted.

### CODE REVIEW

**Comment by MusharrafSakran** [comment]
Thanks. Postgres

**Comment by jricher** [comment]
OK, I'd like confirmation on other platforms before we pull this, so anyone that can test easily on MySQL or Oracle please do so.

**Comment by dsbenghe** [comment]
Any plan to handle the db schema changes using liquibase? Moving the schema to liquibase will make heaps easier to support multiple dbs (we used to run 1.2.5 on Sql Server) and also easier to get contributions to improve the schema like this one.

We have a liquibase schema done based on 1.2.5 schema + some additional indexes and unique constraints which we can contribute.

**Comment by jricher** [comment]
No current plans to use liquibase.

**Comment by jricher** [comment]
Tested on HSQL and MySQL, seems to work fine. Rebased and committed as d862ba9fd8224f8413cb7d074bb171c88c239efa thanks!

**Pull request closed without merging**
