### PR TITLE
db initializer compatibility (pgSql & mySql)

### PR DESCRIPTION
**Pull request by Neths**
for pgSql and mySql :
- add db init script
- add data-context example

### CODE REVIEW

**Comment by isedrof** [comment]
You're using the master branch ?

**Comment by Neths** [comment]
Yes

**Comment by isedrof** [comment]
i tried to do the same but Tomcat does not want to Start the project 
When i look to catalania.out (tomcat logs) i fould an error which say :  Could not load class of driverClassName com.mysql.cj.jdbc.Driver
i don't know why

**Comment by Neths** [comment]
check your pom file or your layout pom if jdbc driver are referenced

**Comment by isedrof** [comment]
<dependency>
                                <groupId>mysql</groupId>
                                <artifactId>mysql-connector-java</artifactId>
                                <version>6.0.5</version>
                        </dependency>

and i want to say that, when i check my database , i notice that tables 've be created

**Comment by Neths** [comment]
follow this wiki page : https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Maven-Overlay-Project-How-To

**Comment by isedrof** [comment]
Why should i create this in the same foder of my MitreId connect server ?
and when i'll get the WAR, should i put in the Tomcat/webapps/ directory ?





2016-12-02 16:21 GMT+01:00 Neths <notifications@github.com>:

**Comment by jricher** [comment]
Rebased and committed as 1b7612a26d31a0119c4c4d26f54e87297aa45a93 and cbe6b9e1df32badbe40c909ba19c7f1c8b7bcd9c

Thanks!

**Comment by isedrof** [comment]
I tired the 1.2.x branch to make a MySQL connectio but it does not work.

**Pull request closed without merging**
