### PR TITLE
Fix NPE when checking claim extension, Simplify always true expressions

### PR DESCRIPTION
**Pull request by leonard84**
The current implementation does not check for null and will throw a NPE on the `toString()` call.
Furthermore I've fixed some wrong javadoc and removed always true expressions in if clauses.

### CODE REVIEW

**Comment by leonard84** [comment]
@jricher is there anything blocking this fix?

**Comment by jricher** [comment]
Limited time and ability to work on pull requests.

**Comment by leonard84** [comment]
Is there any timeline when this can be merged and when the next version will be released? Currently we are forced on include a fake `claims` parameter outside of the `request` parameter to avoid this NPE.

**Comment by jricher** [comment]
Rebased and committed as 8e71107f9ba5a43e573388a0ae199079880a50ce, thanks!

**Comment by leonard84** [comment]
@jricher when is the next release planned that contains this fix?

**Comment by jricher** [comment]
We don't have a solid release date in mind at this time. There are a couple additional changes that will likely change the data storage model that we want to get in before locking down 1.3.0, but time is unfortunately limited in pushing this out.

**Pull request closed without merging**
